name: Test Coverage Uploader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Build with Tests
      run: mvn clean install --file pom.xml
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: unit_tests
